---
- name: Testing my first playbook
  hosts: WindowsServers
  tasks:
  - name: Start and set pooler service to automatic
    win_service:
      name: spooler
      start_mode: auto
      state: started