---
- name: Testing my first playbook
  hosts: exc1.christounet.org
  tasks:
  - Name: Start and set pooler service to automatic
    win_service:
      name: spooler
      start_mode: auto
      state: started